{% assign contributeLink = '//github.com/rash-sh/rash/blob/master/CONTRIBUTING.md#how-to-contribute' %}
{% assign emailLink = 'mailto:pando855@gmail.com' %}
{% assign featureRequestLink = '//github.com/rash-sh/rash/issues' %}
{% assign gettingStartedLink = '/docs/rash/' | append: site.data.projects[0].versions[site.current_release_index].version | append: '/getting_started.html#quickstart' | relative_url %}
{% assign githubLink = '//github.com/rash-sh/rash' %}
{% assign latestDocs = '/docs/rash/' | append: site.data.projects[0].versions[site.current_release_index].version | append: '/' | relative_url %}
